### ISSUE TITLE
Can I disable the translate popup and save the password?

### ISSUE THREAD

**Issue by builuc1998** [chromedp/chromedp#1117]
Hello I am currently using chromedp and facing the problem that when visiting a certain website or logging in, it shows a popup. i tried to find a lot of ways to turn it off but no success. Anyone know how to turn it off please help me. Thank you very much

below is my initialization code
```go
myDefaultExecAllocatorOptions := [...]chromedp.ExecAllocatorOption{
chromedp.NoFirstRun,
chromedp.NoDefaultBrowserCheck,

// After Puppeteer's default behavior.
chromedp.Flag("disable-background-networking", true),
chromedp.Flag("enable-features", "NetworkService,NetworkServiceInProcess"),
chromedp.Flag("disable-background-timer-throttling", true),
chromedp.Flag("disable-backgrounding-occluded-windows", true),
chromedp.Flag("disable-breakpad", true),
chromedp.Flag("disable-client-side-phishing-detection", true),
chromedp.Flag("disable-default-apps", true),
chromedp.Flag("disable-dev-shm-usage", true),
chromedp.Flag("disable-extensions", true),
chromedp.Flag("disable-features", "site-per-process,TranslateUI,BlinkGenPropertyTrees"),
chromedp.Flag("disable-hang-monitor", true),
chromedp.Flag("disable-ipc-flooding-protection", true),
chromedp.Flag("disable-popup-blocking", true),
chromedp.Flag("disable-prompt-on-repost", true),
chromedp.Flag("disable-renderer-backgrounding", true),
chromedp.Flag("disable-sync", true),
chromedp.Flag("force-color-profile", "srgb"),
chromedp.Flag("metrics-recording-only", true),
chromedp.Flag("safebrowsing-disable-auto-update", true),
chromedp.Flag("enable-automation", true),
chromedp.Flag("password-store", "basic"),
chromedp.Flag("use-mock-keychain", true),
chromedp.Flag("disable-web-security", true),
}
```

**Comment by ZekeLu** [comment]
For the translate popup, the feature name has been changed from `TranslateUI` to `Translate`. See https://github.com/chromedp/chromedp/pull/796.

You should create the options like this:

```go
	myDefaultExecAllocatorOptions := append(chromedp.DefaultExecAllocatorOptions[:],
		// only add the options that are not provided by chromedp.DefaultExecAllocatorOptions
		// and that need to be changed below.
	)
```

This should fix the translate popup issue. Maybe it will address the password popup issue too. Please comment if it doesn't.

**Comment by builuc1998** [comment]
I used it according to your instructions but the save password popup still shows up every time I log in.
`
myDefaultExecAllocatorOptions := append(chromedp.DefaultExecAllocatorOptions[:],
		// only add the options that are not provided by chromedp.DefaultExecAllocatorOptions
		// and that need to be changed below.
	)
`

**Comment by ZekeLu** [comment]
It seems that it can only be disabled by using the profile (or policy). See https://github.com/chromedp/chromedp/issues/1095 for information about the profile file. And see https://chromeenterprise.google/policies/?policy=PasswordManagerEnabled for information about the browser policy.

```json
{
  "credentials_enable_service": false
}
```

**Comment by builuc1998** [comment]
> It seems that it can only be disabled by using the profile (or policy).
> 
> ```json
> {
>   "credentials_enable_service": false
> }
> ```
> 
> References:
> 
> * [how to config 'prefs' in chromedp #1095](https://github.com/chromedp/chromedp/issues/1095)
> * https://chromeenterprise.google/policies/?policy=PasswordManagerEnabled
> * https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/password_manager/password_manager_settings_service_impl.cc;l=21;drc=97f94c6631e327c2c1a9891774b44fbba9e8e3bf;bpv=1;bpt=1

Thank you very much
