### ISSUE TITLE
Full xpath selector being computed incorrectly

### ISSUE THREAD

**Issue by bbeck** [chromedp/chromedp#133]
I've noticed that at times that full xpath selector (algorithm here: https://github.com/knq/chromedp/blob/master/cmd/chromedp-gen/templates/extra.qtpl#L108-L150) for a DOM element gets computed incorrectly.  I've visually inspected this code quite a bit and can't spot an obvious error in it, but I can reproduce it generating an incorrect xpath selector consistently.  This doesn't happen all the time.

The way that this problem manifests itself for me is when I call `WaitVisible` on an element and chromedp generates a sequence of events like:

```
2017/11/08 08:35:07 <- {"id":322,"method":"DOM.querySelector","params":{"nodeId":163,"selector":"input[type=password][name=passwd]"}}
2017/11/08 08:35:07 -> {"id":322,"result":{"nodeId":374}}

2017/11/08 08:35:07 <- {"id":323,"method":"DOM.getBoxModel","params":{"nodeId":374}}
2017/11/08 08:35:07 -> {"id":323,"result":{"model":{"content":[370,536,686,536,686,558,370,558],"padding":[360,530,696,530,696,564,360,564],"border":[359,529,697,529,697,565,359,565],"margin":[359,529,697,529,697,565,359,565],"width":338,"height":36}}}

2017/11/08 08:35:07 <- {"id":324,"method":"Runtime.evaluate","params":{"expression":"(function(a) {\n\t\treturn a[0].offsetParent !== null;\n\t})($x('/html[1]/body[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/input[1]'))","objectGroup":"console","includeCommandLineAPI":true,"returnByValue":true}}
2017/11/08 08:35:07 -> {"id":324,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'offsetParent' of undefined\n    at \u003Canonymous\u003E:2:15\n    at \u003Canonymous\u003E:3:4","objectId":"{\"injectedScriptId\":18,\"id\":143}"},"exceptionDetails":{"exceptionId":73,"text":"Uncaught","lineNumber":1,"columnNumber":14,"scriptId":"262","stackTrace":{"callFrames":[{"functionName":"","scriptId":"262","url":"","lineNumber":1,"columnNumber":14},{"functionName":"","scriptId":"262","url":"","lineNumber":2,"columnNumber":3}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read property 'offsetParent' of undefined\n    at \u003Canonymous\u003E:2:15\n    at \u003Canonymous\u003E:3:4","objectId":"{\"injectedScriptId\":18,\"id\":144}"}}}}
```

As you can see on `id:324` it's calling the `visibleJS` snippet with an xpath expression to the element.  The xpath expression evaluates to undefined so there's an error returned.  In this particular case I've worked out by hand the proper xpath expression and it's: `$x('/html[1]/body[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/input[1]')`.  The only change was `div[4]` -> `div[3]`.

I've created a gist that reproduces this problem reliably here: https://gist.github.com/bbeck/c26e759bf63cb7e3040f0aa763f5c897

I've also experimented with tweaking chromedp to use `PartialXPathByID()` everywhere that it currently uses `FullXPath()` and that does seem to fix my instance of the problem, but I suspect that's just masking the issue as it's the same underlying code.

I'd appreciate any insight you might have on what's going on here and how to fix it.

**Comment by kenshaw** [comment]
Thanks for the research on this. I'll look into it and see if what the issue is. What version of Chrome are you using?

**Comment by bbeck** [comment]
I've seen this happen on multiple versions of Chrome on OS X, but just reproduced it on Version 62.0.3202.94 which is the latest stable version I believe.

**Comment by jcrussell** [comment]
I added some `log.Printf`s to try to figure this out. It looks like the wrong `*Node` is getting updated during an `EventChildNodeRemoved`. 

In `childNodeRemoved`, I printed the node to delete, the parent node, and the children IDs before and after calling `removeNode`. This is what the output looks like:

```
removing child 182 from 157
children before: [158]
children after: [158]
```

In `cdp.Node.xpath`, I printed the node ID and the children IDs. This is what the output looks like:

```
finding xpath for 157, children: [158, 159, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180]
```

There are no `EventChildNodeInserted` events between the handling of the `EventChildNodeRemoved` and the call to `cdp.Node.xpath`.

If node 182 was deleted, then the indices would be correct as @bbeck mentioned (The only change was div[4] -> div[3]).

I'm going to keep tinkering but hopefully this will jog your memory as to where to look.

**Comment by kenshaw** [comment]
@jcrussell thanks for the input. Do you have a script or some such that can reproduce this easily, so I don't need to waste time writing stuff from scratch?

**Comment by bbeck** [comment]
@kenshaw I linked a gist in my original message that consistently reproduces the problem.

https://gist.github.com/bbeck/c26e759bf63cb7e3040f0aa763f5c897

**Comment by jcrussell** [comment]
Slightly modified version of @bbeck's gist: https://gist.github.com/jcrussell/17e11caad212e4147e878840538847dd

Some relevant snippets from the output (node IDs are different from my previous comment):

```
2017/11/27 18:58:24 handling EventChildNodeRemoved
2017/11/27 18:58:24 removing child 195 from 170
2017/11/27 18:58:24 children before: [171]
2017/11/27 18:58:24 children after: [171]
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":193,"nodes":[{"nodeId":215,"parentId":193,"backendNodeId":215,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":"Enter password"}]}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":193,"pseudoElement":{"nodeId":216,"backendNodeId":216,"nodeType":1,"nodeName":"<pseudo:before>","localName":"<pseudo:before>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"before"}}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":193,"pseudoElement":{"nodeId":217,"backendNodeId":217,"nodeType":1,"nodeName":"<pseudo:after>","localName":"<pseudo:after>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"after"}}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":197,"nodes":[{"nodeId":218,"parentId":197,"backendNodeId":218,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":2,"attributes":["class","form-group col-md-24"]}]}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":197,"pseudoElement":{"nodeId":219,"backendNodeId":219,"nodeType":1,"nodeName":"<pseudo:before>","localName":"<pseudo:before>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"before"}}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":197,"pseudoElement":{"nodeId":220,"backendNodeId":220,"nodeType":1,"nodeName":"<pseudo:after>","localName":"<pseudo:after>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"after"}}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":202,"nodes":[{"nodeId":221,"parentId":202,"backendNodeId":221,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":0,"children":[{"nodeId":222,"parentId":221,"backendNodeId":222,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":" "}],"attributes":["data-bind","component: { name: 'footer-buttons-field',\n        params: {\n            serverData: svr,\n            primaryButtonText: str['CT_PWD_STR_SignIn_Button'],\n            isPrimaryButtonEnabled: !isRequestPending(),\n            isPrimaryButtonVisible: svr.AN,\n            isSecondaryButtonEnabled: true,\n            isSecondaryButtonVisible: svr.AN && isBackButtonVisible() },\n        event: {\n            primaryButtonClick: primaryButton_onClick,\n            secondaryButtonClick: secondaryButton_onClick } }"]}]}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":202,"pseudoElement":{"nodeId":223,"backendNodeId":223,"nodeType":1,"nodeName":"<pseudo:before>","localName":"<pseudo:before>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"before"}}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":202,"pseudoElement":{"nodeId":224,"backendNodeId":224,"nodeType":1,"nodeName":"<pseudo:after>","localName":"<pseudo:after>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"after"}}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":204,"nodes":[{"nodeId":225,"parentId":204,"backendNodeId":225,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":0,"attributes":["id","swv-warning","class","wrap-content","data-bind","text: str['CT_PWD_STR_PersistentCookies_Warning']"]}]}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":204,"pseudoElement":{"nodeId":226,"backendNodeId":226,"nodeType":1,"nodeName":"<pseudo:before>","localName":"<pseudo:before>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"before"}}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":204,"pseudoElement":{"nodeId":227,"backendNodeId":227,"nodeType":1,"nodeName":"<pseudo:after>","localName":"<pseudo:after>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"after"}}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":209,"nodes":[{"nodeId":228,"parentId":209,"backendNodeId":228,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":1,"attributes":["class","col-md-24"]}]}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":209,"pseudoElement":{"nodeId":229,"backendNodeId":229,"nodeType":1,"nodeName":"<pseudo:before>","localName":"<pseudo:before>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"before"}}}
2017/11/27 18:58:24 -> {"method":"DOM.pseudoElementAdded","params":{"parentId":209,"pseudoElement":{"nodeId":230,"backendNodeId":230,"nodeType":1,"nodeName":"<pseudo:after>","localName":"<pseudo:after>","nodeValue":"","childNodeCount":0,"attributes":[],"pseudoType":"after"}}}
2017/11/27 18:58:24 -> {"method":"DOM.childNodeRemoved","params":{"parentNodeId":170,"nodeId":199}}
2017/11/27 18:58:24 handling EventChildNodeRemoved
2017/11/27 18:58:24 removing child 199 from 170
2017/11/27 18:58:24 children before: [171]
2017/11/27 18:58:24 children after: [171]
2017/11/27 18:58:24 -> {"method":"DOM.childNodeInserted","params":{"parentNodeId":221,"previousNodeId":0,"node":{"nodeId":231,"backendNodeId":231,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":2,"attributes":["class","col-xs-24 form-group no-padding-left-right","data-bind","\n     visible: isPrimaryButtonVisible() || isSecondaryButtonVisible(),\n     css: { 'no-margin-bottom': removeBottomMargin }"]}}}
2017/11/27 18:58:24 -> {"method":"DOM.childNodeRemoved","params":{"parentNodeId":170,"nodeId":204}}
2017/11/27 18:58:24 handling EventChildNodeRemoved
2017/11/27 18:58:24 removing child 204 from 170
2017/11/27 18:58:24 children before: [171]
2017/11/27 18:58:24 children after: [171]
2017/11/27 18:58:24 -> {"method":"DOM.childNodeRemoved","params":{"parentNodeId":170,"nodeId":211}}
2017/11/27 18:58:24 handling EventChildNodeRemoved
2017/11/27 18:58:24 removing child 211 from 170
2017/11/27 18:58:24 children before: [171]
2017/11/27 18:58:24 children after: [171]
2017/11/27 18:58:24 -> {"method":"DOM.inlineStyleInvalidated","params":{"nodeIds":[]}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":218,"nodes":[{"nodeId":232,"parentId":218,"backendNodeId":232,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":2,"attributes":["role","alert","aria-live","assertive","aria-atomic","false"]},{"nodeId":233,"parentId":218,"backendNodeId":233,"nodeType":1,"nodeName":"DIV","localName":"div","nodeValue":"","childNodeCount":7,"attributes":["class","placeholderContainer","data-bind","component: { name: 'placeholder-textbox', params: {\n            serverData: svr,\n            textInput: password,\n            hasFocus: isFocused,\n            hintText: str['CT_PWD_STR_PwdTB_Label'],\n            forcePlaceholderAttribute: true,\n            hintCss: 'placeholder' } }"]}]}}
2017/11/27 18:58:24 -> {"method":"DOM.setChildNodes","params":{"parentId":233,"nodes":[{"nodeId":234,"parentId":233,"backendNodeId":234,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" ko withProperties: { '$placeholderText': placeholderText } "},{"nodeId":235,"parentId":233,"backendNodeId":235,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" ko template: { nodes: $componentTemplateNodes, data: $parent } "},{"nodeId":236,"parentId":233,"backendNodeId":236,"nodeType":1,"nodeName":"INPUT","localName":"input","nodeValue":"","childNodeCount":0,"children":[],"attributes":["name","passwd","type","password","id","i0118","autocomplete","off","class","form-control","aria-describedby","passwordError loginHeader passwordDesc","aria-required","true","data-bind","\n                    textInput: password,\n                    hasFocusEx: isFocused,\n                    placeholder: $placeholderText,\n                    ariaLabel: str['CT_PWD_STR_PwdTB_AriaLabel'],\n                    css: { 'has-error': error }","placeholder","Password","aria-label","Enter password"],"shadowRoots":[{"nodeId":237,"backendNodeId":237,"nodeType":11,"nodeName":"#document-fragment","localName":"","nodeValue":"","childNodeCount":2,"shadowRootType":"user-agent"}]},{"nodeId":238,"parentId":233,"backendNodeId":238,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" /ko "},{"nodeId":239,"parentId":233,"backendNodeId":239,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" /ko "},{"nodeId":240,"parentId":233,"backendNodeId":240,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" ko ifnot: forcePlaceholderAttribute "},{"nodeId":241,"parentId":233,"backendNodeId":241,"nodeType":8,"nodeName":"#comment","localName":"","nodeValue":" /ko "}]}}
2017/11/27 18:58:24 -> {"id":98,"result":{"nodeId":236}}
2017/11/27 18:58:24 -> {"method":"Page.lifecycleEvent","params":{"name":"networkAlmostIdle","timestamp":365693.235903}}
2017/11/27 18:58:24 unhandled page event *page.EventLifecycleEvent
2017/11/27 18:58:24 <- {"id":99,"method":"DOM.getBoxModel","params":{"nodeId":236}}
2017/11/27 18:58:24 -> {"id":99,"result":{"model":{"content":[310,459,626,459,626,481,310,481],"padding":[300,453,636,453,636,487,300,487],"border":[299,452,637,452,637,488,299,488],"margin":[299,452,637,452,637,488,299,488],"width":338,"height":36}}}
2017/11/27 18:58:24 finding xpath for 236 input
2017/11/27 18:58:24 children:
2017/11/27 18:58:24 finding xpath for 233 div
2017/11/27 18:58:24 children:
2017/11/27 18:58:24 	234 
2017/11/27 18:58:24 	235 
2017/11/27 18:58:24 	236 input
2017/11/27 18:58:24 	238 
2017/11/27 18:58:24 	239 
2017/11/27 18:58:24 	240 
2017/11/27 18:58:24 	241 
2017/11/27 18:58:24 finding xpath for 218 div
2017/11/27 18:58:24 children:
2017/11/27 18:58:24 	232 div
2017/11/27 18:58:24 	233 div
2017/11/27 18:58:24 finding xpath for 197 div
2017/11/27 18:58:24 children:
2017/11/27 18:58:24 	218 div
2017/11/27 18:58:24 finding xpath for 170 div
2017/11/27 18:58:24 children:
2017/11/27 18:58:24 	171 
2017/11/27 18:58:24 	172 
2017/11/27 18:58:24 	173 input
2017/11/27 18:58:24 	175 input
2017/11/27 18:58:24 	177 input
2017/11/27 18:58:24 	179 input
2017/11/27 18:58:24 	181 input
2017/11/27 18:58:24 	183 input
2017/11/27 18:58:24 	185 input
2017/11/27 18:58:24 	187 input
2017/11/27 18:58:24 	189 input
2017/11/27 18:58:24 	191 div
2017/11/27 18:58:24 	193 div
2017/11/27 18:58:24 	194 
2017/11/27 18:58:24 	195 div
2017/11/27 18:58:24 	196 
2017/11/27 18:58:24 	197 div
2017/11/27 18:58:24 	198 
```

**Comment by kenshaw** [comment]
Thanks, appreciate it. I'll look into it possibly later today.

**Comment by jcrussell** [comment]
After looking at `TargetHandler.domEvent`, I think that DOM events are being processed in the wrong order -- events are processed in the order that they acquire the locks instead of the order they arrive.

To confirm, I added a counter to `TargetHandler` and incremented it in `processEvent` before handing it as an extra parameter to `domEvent`. I then logged the parameter before calling `op(n)`. This confirmed that events are being processed out of order.

I changed it so that `domEvent` is not called with a Goroutine and the gist works. However, now I see timeouts waiting for nodes on my use case. Perhaps the DOM events need to go back into a channel so that a single Goroutine processes them in order?

**Comment by kenshaw** [comment]
The issue really is the fundamental problem with the remaining issues, which is simply that we're not keeping track of the network loaders, which is a problem. A new update is coming that will simultaneously add this, and should fix this issue.

**Comment by AmrAlfoly** [comment]
and please add the implementation for the cdp.CloseByIndex() and cdp.CloseById()

**Comment by antisnatchor** [comment]
Hey @kenshaw , any updates on this?  

I still have the same issue of @jcrussell  on Chrome 64.0.3282.167( Linux) using golang 1.9.4.

Btw, your tool rocks! 

Thanks
anti

**Comment by SylvainGarrigues** [comment]
Still having the same issue here with latest Chrome on MacOS.

**Comment by pbar1** [comment]
This looks awfully familiar :smirk: 
I'm experiencing this exact same issue when trying to login with Azure AD using chromedp.

```
Chromium: Version 68.0.3440.106 (Official Build) Arch Linux (64-bit)
Go: go version go1.10.3 linux/amd64
```

**Comment by mvdan** [comment]
Sounds like this is the same underlying issue as #168. Let's merge all the discussion there.
