### ISSUE TITLE
unmarshal/parse errors on master

### ISSUE THREAD

**Issue by tmm1** [chromedp/chromedp#598]
I upgraded chromedp as follows:

```diff
-       github.com/chromedp/cdproto v0.0.0-20191114225735-6626966fbae4
-       github.com/chromedp/chromedp v0.5.3-0.20191127221454-aa5cc8729d94
+       github.com/chromedp/cdproto v0.0.0-20200116234248-4da64dd111ac
+       github.com/chromedp/chromedp v0.5.4-0.20200327135129-ea717c104aa0
```

And now I'm seeing lots of errors:

```
2020/04/10 10:22:33.429438 ERROR: could not unmarshal event: parse error: expected string near offset 246 of 'headers'
2020/04/10 10:22:33.733418 ERROR: could not unmarshal event: parse error: expected string near offset 79 of 'headers'
2020/04/10 10:22:33.906118 ERROR: could not unmarshal event: parse error: expected string near offset 79 of 'headers'
2020/04/10 10:22:33.906360 ERROR: could not unmarshal event: parse error: expected string near offset 4465 of 'headers'
2020/04/10 10:22:34.028244 ERROR: could not unmarshal event: parse error: expected string near offset 79 of 'headers'
2020/04/10 10:22:34.240955 ERROR: could not unmarshal event: parse error: expected string near offset 79 of 'headers'
2020/04/10 10:22:34.247000 ERROR: could not unmarshal event: parse error: expected string near offset 2356 of 'headers'
2020/04/10 10:22:34.286561 ERROR: could not unmarshal event: parse error: expected string near offset 2386 of 'headers'
2020/04/10 10:22:34.287159 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.311633 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.349631 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.350393 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.350885 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.357037 ERROR: could not unmarshal event: parse error: expected string near offset 55 of 'headers'
2020/04/10 10:22:34.364281 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.370560 ERROR: could not unmarshal event: parse error: expected string near offset 55 of 'headers'
2020/04/10 10:22:34.411322 ERROR: could not unmarshal event: parse error: expected string near offset 54 of 'headers'
2020/04/10 10:22:34.414674 ERROR: could not unmarshal event: parse error: expected string near offset 55 of 'headers'
2020/04/10 10:22:34.421384 ERROR: could not unmarshal event: parse error: expected string near offset 55 of 'headers'
2020/04/10 10:22:34.421433 ERROR: could not unmarshal event: parse error: expected string near offset 55 of 'headers'
```

**Comment by tmm1** [comment]
I'm using:

>Chromium 79.0.3945.130

the error seems to be coming from here:

https://github.com/chromedp/chromedp/blob/2c48f1180a35d8e790f47a6aa601667873f75ce0/target.go#L75

**Comment by tmm1** [comment]
Same thing also happening on macOS with:

>Google Chrome 80.0.3987.163

**Comment by tmm1** [comment]
Looks like this is fixed in the latest cdproto.

```diff
-       github.com/chromedp/cdproto v0.0.0-20200116234248-4da64dd111ac
+       github.com/chromedp/cdproto v0.0.0-20200209033844-7e00b02ea7d2
```

**Comment by mvdan** [comment]
I also saw event unmarshal errors when running the tests on master with chromium v81, and I've updated the cdproto minimum version. Is this enough for you, or is your issue persisting? Because I didn't see exactly the same errors.

**Comment by tmm1** [comment]
Everything seems to be fine with the updated cdproto. Thanks!
