### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by msoap** [chromedp/chromedp#823]
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.2
$ chromium-browser --version
Chromium 90.0.4430.93 Built on Ubuntu , running on Ubuntu 18.04
$ go version
go version go1.16.3 darwin/amd64
program cross-compiled with `GOOS=linux CGO_ENABLED=0`
</pre>

#### What did you do? Include clear steps.
We have a server that launches browsers, executes commands on them and terminates them
```
	allocContext, c.allocCancel = chromedp.NewExecAllocator(context.Background(), runnerOptions...)
	...
	c.ctx, c.cancel = chromedp.NewContext(allocContext, options...)

	...
		chromedp.ListenTarget(c.ctx, func(event interface{}) {
		switch ev := event.(type) {
		case *network.EventRequestWillBeSent:
			c.netMutex.Lock()
			c.pendingRequests++
			if c.netEvents == nil {
				c.netEvents = make(map[string]*RoundTrip)
			}
			if _, ok := c.netEvents[string(ev.RequestID)]; !ok {
				r := &RoundTrip{
					Tag:            string(ev.RequestID),
					Method:         ev.Request.Method,
					URL:            ev.Request.URL,
					RequestHeaders: ev.Request.Headers,
				}
				c.netEvents[string(ev.RequestID)] = r
				c.network = append(c.network, r)
			}
			c.netMutex.Unlock()
		case *network.EventResponseReceived:
			c.netMutex.Lock()
			c.pendingRequests--
			if r, ok := c.netEvents[string(ev.RequestID)]; ok {
				r.ResponseCode = ev.Response.Status
				r.ResponseHeaders = ev.Response.Headers
				r.Type = string(ev.Type)
			} else {
				log.Printf("Event %s not registered", ev.RequestID)
			}
			c.netMutex.Unlock()
		}
	})

	...
	chromedp.Run(c.ctx, tasks...)
	...
	chromedp.Cancel(c.ctx)
	c.cancel()
	c.allocCancel()

```
this server lives under load, about several browsers per minute, and falls from time to time with panic, about 2 times in the last day.

#### What did you see instead?
Panic:

```
panic: close of closed channel
goroutine 607199 [running]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0xc001110840, 0x0, 0xc0012c1700, 0x1e, 0xc00128ef20, 0xc0000ad0e0)
#011/Users/msa/go/pkg/mod/github.com/chromedp/chromedp@v0.7.2/allocate.go:214 +0x6a
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
#011/Users/msa/go/pkg/mod/github.com/chromedp/chromedp@v0.7.2/allocate.go:200 +0xa4f
```

**Comment by ZekeLu** [comment]
I can reproduce the same panic with the following carefully crafted program:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		// in order to make cmd.Wait() (see the link below) returns soon enough,
		// specify an executable that will exit immediately.
		// https://github.com/chromedp/chromedp/blob/f50e6240fa873d8c103c54a028b78266f4b09138/allocate.go#L215
		chromedp.ExecPath("echo"),
	)
	allocatorCtx, allocatorCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer allocatorCancel()
	browserCtx, browserCancel := chromedp.NewContext(allocatorCtx)
	defer browserCancel()

	for i := 0; i < 2; i++ {
		go func() {
			// the new browser context (browser are not created yet) are used concurrently
			if err := chromedp.Run(browserCtx,
				chromedp.Navigate("https://www.google.com/"),
			); err != nil {
				log.Print(err)
			}
		}()
	}

	time.Sleep(2 * time.Second)
}
```

The issue in the code is that the _new_ browser context (_new_ means the browser process is not created yet) is used by `chromedp.Run()` concurrently.

You store the context in `c.ctx`, and use it later. It's not clear how `c` and `c.ctx` are managed in your project, but it's very likely that `c.ctx` is used by multiple goroutines and it failed the same way as my demo.

The fix is straightforward - just avoid using the new browser context concurrently. You can create a browser process first (use lock to make sure just one goroutine is doing this job if needed), and then it's safe to create multiple tabs in this browser concurrently.

**Comment by msoap** [comment]
@ZekeLu yes, the c.ctx is used concurrently, I'll try to fix it.
Thanks.

**Comment by ZekeLu** [comment]
Similar issue #597.

**Comment by msoap** [comment]
After few days and fix concurrency I don't see panic, thanks.

**Comment by qin-nz** [comment]
@msoap Is it fixd? I see it in v0.9.1

```
panic: close of closed channel

goroutine 10874 [running]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2()
        /home/users/xxx/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/allocate.go:236 +0xe5
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
        /home/users/xxx/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/allocate.go:217 +0xdf2
```

**Comment by ZekeLu** [comment]
@qin-nz `allocate.go:236` is the only place that `c.allocated` is closed. If you see `panic: close of closed channel`,  it usually means that you don't use the context or the allocator correctly (the demo in https://github.com/chromedp/chromedp/issues/823#issuecomment-843329591 is one of the case). I don't think it has  anything to do with `sandbox`. If you would like us to look into it, please provide a reproducer. Thank you!

https://github.com/chromedp/chromedp/blob/6e7da0b95f211a7dc9663385898b6068c603d6d7/allocate.go#L236

**Comment by qin-nz** [comment]
@ZekeLu I fixed it~ 
I have an clean installed CentOS 7.6, then I use `yum install -y chromium-headless` to install headless version only. 
This problem happend.
Then I try run `yum install -y chromium-browser chromium` without changing any code.
The problem disappered.

**Comment by ZekeLu** [comment]
You don't understand what the issue is. The issue could be hidden by how you run the browser or which browser you use. But the issue is still there.
